// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var loanOrders = LoanOrders.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class LoanOrders
    {

        [JsonProperty("offers")]
        public List<Demand> Offers { get; set; }

        [JsonProperty("demands")]
        public List<Demand> Demands { get; set; }
    }

    public partial class Demand
    {
        [JsonProperty("rate")]
        public string Rate { get; set; }

        [JsonProperty("amount")]
        public string Amount { get; set; }

        [JsonProperty("rangeMin")]
        public long RangeMin { get; set; }

        [JsonProperty("rangeMax")]
        public long RangeMax { get; set; }
    }

    public partial class LoanOrders
    {
        public static LoanOrders FromJson(string json) => JsonConvert.DeserializeObject<LoanOrders>(json, QuickType.Converter.Settings);
    }


}
